{
 "title": "Consul Service Dashboard",
 "description": "Envoy proxy monitoring Dashboard with cluster and service level templates. ",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(envoy_server_live, app)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{service=~\"$service\"}, envoy_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_working_set_bytes, namespace)"
    }
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   {
    "name": "test",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{service=~\"$service\"}, envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\", envoy_response_code_class!=\"4\",consul_destination_service=~\"$service\"}[10m])) / sum(irate(envoy_cluster_upstream_rq_xx{consul_destination_service=~\"$service\"}[10m])) "
    }
   ]
  },
  {
   "title": "Total Failed Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=~\"4|5\", consul_destination_service=~\"$service\"}[10m]))by(local_cluster)",
     "legendFormat": "{{consul_destination_service}}"
    }
   ]
  },
  { "title": "TCP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "TCP Downstream Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "envoy_tcp_downstream_cx_total{}"
    }
   ]
  },
  {
   "title": "TCP Downstream Connection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "envoy_tcp_max_downstream_connection_duration{}"
    }
   ]
  },
  { "title": "Service Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Running Services",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 1, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{app!=\"traffic-generator\"})"
    }
   ]
  },
  {
   "title": "Connections Rejected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_cx_overload_reject{}[$__interval])",
     "legendFormat": "{{namespace}} : {{consul_source_service}}-{{envoy_listener_address}}-overload"
    },
    {
     "expr": "rate(envoy_listener_downstream_global_cx_overflow{}[$__interval])",
     "legendFormat": "{{namespace}} : {{consul_source_service}}-{{envoy_listener_address}}-overflow"
    }
   ]
  },
  {
   "title": "Total active upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 1, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{app=~\"$service\"}) by (app)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Rq by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "sum by(namespace,app,envoy_response_code_class) (rate(envoy_cluster_upstream_rq_xx[5m]))",
     "legendFormat": "{{namespace}} : {{app}}-{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Total active http downstream connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 1, "y": 32 },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{app=~\"$service\"}) by (app)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downstream Rq by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"public_listener\"}[5m])) by (namespace, app,envoy_response_code_class)\n",
     "legendFormat": "{{namespace}} : {{app}}-{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Dataplane Latency ( $service )",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$service\"}[5m])))\n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$service\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$service\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(.999, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$service\"}[5m])))",
     "legendFormat": "p99.9"
    }
   ]
  }
 ]
}