{
 "title": "Consul K8s monitoring (control plane)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Consul Servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "consul_consul_server_0_consul_members_servers{pod=\"consul-server-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Connected Consul-dataplanes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(consul_dataplane_envoy_connected)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Utilization (Consul Servers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CPU Usage in Seconds (Consul servers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"consul\", pod=~\"consul-server-.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Consul servers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"consul\", pod=~\"consul-server-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read/Write total per 5 minutes (Consul servers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"consul-server-.*\", container=\"consul\"}[5m])) by (pod, device)",
     "legendFormat": "writes, {pod=\"{{pod}}\"}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"consul-server-.*\", container=\"consul\"}[5m])) by (pod, device)",
     "legendFormat": "reads, {pod=\"{{pod}}\"}"
    }
   ]
  },
  {
   "title": "Received bytes total per 5 minutes (Consul servers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"consul-server-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit (Consul Servers)",
   "type": "gauge",
   "description": "All consul servers have the same limit",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=\"consul-server-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit in Seconds (Consul Servers)",
   "type": "gauge",
   "description": "All consul servers have the same limit",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", pod=\"consul-server-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage (Consul servers)",
   "type": "gauge",
   "description": "Gives the filesystem storage used by consul servers",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod=\"consul-server-0\"}) "
    }
   ]
  },
  {
   "title": "Resource Utilization (Connect Injector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "CPU Usage in Seconds (Connect Injector)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\".*-connect-injector-.*\",container=\"sidecar-injector\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit in Seconds (Connect Injector)",
   "type": "gauge",
   "description": "All consul servers have the same limit",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\", container=\"sidecar-injector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Connect Injector)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\".*-connect-injector-.*\",container=\"sidecar-injector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit (Connect Injector)",
   "type": "gauge",
   "description": "All consul servers have the same limit",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\", container=\"sidecar-injector\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}