{
 "title": "Consul DataPlane Access Logs and Errors",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(envoy_server_live, app)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{service=~\"$service\"}, envoy_cluster_name)"
    }
   },
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "searchable_pattern",
    "label": "Search (case insensitive)",
    "query": "\"response_code\":200"
   }
  ]
 },
 "panels": [
  {
   "title": "Total logs",
   "type": "stat",
   "description": "Total Count of log lines in the specified time range",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"consul-dataplane\",namespace=~\"$namespace\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total logs containing \"$searchable_pattern\"",
   "type": "stat",
   "description": "Total count of logs containing the search filter term in the specified time range",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"consul-dataplane\", namespace=~\"$namespace\"} |~ `(?i)(?i)$searchable_pattern` [$__interval]))"
    }
   ]
  },
  {
   "title": "Percentage of logs containing \"$searchable_pattern\"",
   "type": "stat",
   "description": "Percentage of logs containing the search filter term in the specified time range",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({container=\"consul-dataplane\", namespace=~\"$namespace\"} |~ `(?i)(?i)$searchable_pattern` [$__interval])) * 100) / sum(count_over_time({container=\"consul-dataplane\", namespace=~\"$namespace\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Response code distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(response_code) (count_over_time({container=\"consul-dataplane\", namespace=\"$namespace\"} | json | response_code != `0` | __error__=`` [$__range]))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Total logs containing \"$searchable_pattern\" by app",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({container=\"consul-dataplane\", namespace=~\"$namespace\"} |~ `(?i)(?i)$searchable_pattern` [$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of logs containing \"$searchable_pattern\" per app",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(app) (rate({container=\"consul-dataplane\", namespace=~\"$namespace\"} |~ `(?i)(?i)$searchable_pattern` [$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}