{
 "title": "HashiCups",
 "description": "Envoy proxy monitoring Dashboard with cluster and service level templates. ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(envoy_server_live, app)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{service=~\"$service\"}, envoy_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_working_set_bytes, namespace)"
    }
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   {
    "name": "test",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{service=~\"$service\"}, envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "envoy_http_downstream_rq_total{cluster=~\"$cluster\",local_cluster=~\"$service\",envoy_http_conn_manager_prefix=\"public_listener\"}"
    }
   ]
  },
  { "title": "DataPlane Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Mem Usage % by pod limits",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 1, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * max (container_memory_working_set_bytes{namespace=~\"$namespace\"} / on(container, pod) label_replace(kube_pod_container_resource_limits{resource=\"memory\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\")) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %  by pod limits",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max(\n  container_memory_working_set_bytes{namespace=~\"$namespace\"} / \n  on(container, pod) label_replace(kube_pod_container_resource_limits{resource=\"memory\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\")\n) by (pod)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{namespace=~\"$namespace\",envoy_http_conn_manager_prefix=\"public_listener\"}[5m])) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections ( $app )",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app) (envoy_cluster_upstream_cx_active{app=~\"$service\",namespace=~\"$namespace\",envoy_cluster_name!~\"consul-dataplane|prometheus.*|local_app|original-.*\"})",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Dataplane Latency ( $app )",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$service\"}[5m])))\n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$service\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$service\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(.999, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", app=~\"$service\"}[5m])))",
     "legendFormat": "p99.9"
    }
   ]
  },
  { "title": "DataPlane Health Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Running HashiCups services",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 1, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{app!=\"traffic-generator\"})"
    }
   ]
  },
  {
   "title": "Connections Rejected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_cx_overload_reject{}[$__interval])",
     "legendFormat": "{{namespace}} : {{consul_source_service}}-{{envoy_listener_address}}-overload"
    },
    {
     "expr": "rate(envoy_listener_downstream_global_cx_overflow{}[$__interval])",
     "legendFormat": "{{namespace}} : {{consul_source_service}}-{{envoy_listener_address}}-overflow"
    }
   ]
  },
  {
   "title": "Total active upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 1, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{app=~\"$service\"}) by (app)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Rq by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 31 },
   "targets": [
    {
     "expr": "sum by(namespace,app,envoy_response_code_class) (rate(envoy_cluster_upstream_rq_xx[5m]))",
     "legendFormat": "{{namespace}} : {{app}}-{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Total active http downstream connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 1, "y": 38 },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{app=~\"$service\"}) by (app)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downstream Rq by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"public_listener\"}[5m])) by (namespace, app,envoy_response_code_class)\n",
     "legendFormat": "{{namespace}} : {{app}}-{{envoy_response_code_class}}xx"
    }
   ]
  },
  { "title": "Default Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{app=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{app=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{app=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size{app=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy{app=~\"$service\",envoy_cluster_name=~\"$cluster\"})  - sum(envoy_cluster_membership_total{app=~\"$service\",envoy_cluster_name=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{app=~\"$service\",envoy_cluster_name=~\"$cluster\"})-sum(envoy_cluster_membership_healthy{app=~\"$service\",envoy_cluster_name=~\"$cluster\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{app=~\"$service\",envoy_cluster_name=~\"$cluster\"}) by (app,envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} ({{service}})"
    }
   ]
  },
  {
   "title": "Downstream Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{app=~\"$service\"}) by (app)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "{app=~\"frontend|nginx|payments|product-api|product-api-db|public-api\"}"
    }
   ]
  }
 ]
}