{
 "title": "Outbound Traffic Scenarios",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(envoy_server_live, app)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{service=~\"$service\"}, envoy_cluster_name)"
    }
   },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Is this service sending traffic to its upstreams?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{local_cluster=~\"$service\",\nconsul_destination_target!=\"\"}[10m])) by (consul_destination_target)"
    }
   ]
  },
  {
   "title": "Are requests from this service to its upstreams mostly successful?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\",local_cluster=~\"$service\",\nconsul_destination_target!=\"\"}[10m])) by (consul_destination_target) / sum(irate(envoy_cluster_upstream_rq_xx{local_cluster=~\"$service\",consul_destination_target!=\"\"}[10m])) by (consul_destination_target)\n"
    }
   ]
  },
  {
   "title": "Are requests from this service to its upstreams handled in a timely manner?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{local_cluster=~\"$service\",consul_target!=\"\"}[10m])) by (local_cluster))"
    }
   ]
  },
  {
   "title": "Is Envoy's configuration growing stale?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "group(last_over_time(envoy_control_plane_connected_state{cluster=\"$cluster\"}[10m] ) == 0) "
    }
   ]
  }
 ]
}