{
 "title": "Inbound Traffic Scenarios",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(envoy_server_live, app)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{service=~\"$service\"}, envoy_cluster_name)"
    }
   },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Are responses from this service mostly successful? By Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{local_cluster=~\"$service\",envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (envoy_response_code_class)\n"
    }
   ]
  },
  {
   "title": "Are requests sent to this service mostly successful?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\", consul_destination_service=~\"$service\"}[10m])) by (cluster, local_cluster) / sum(irate(envoy_cluster_upstream_rq_xx{consul_destination_service=~\"$service\"}[10m])) by (cluster, local_cluster)"
    }
   ]
  },
  {
   "title": "Are responses from this service mostly successful? Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_total{local_cluster=~\"$service\",envoy_http_conn_manager_prefix=\"public_listener\"}[10m]))"
    }
   ]
  },
  {
   "title": "Are requests sent to this service handled in a timely manner?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_destination_datacenter=\"dc1\",consul_destination_service=~\"$service\",local_cluster!=\"\"}[10m])) by (le, cluster, local_cluster))"
    }
   ]
  },
  {
   "title": "Is this service responding to requests that it receives?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{local_cluster=~\"$service\",envoy_http_conn_manager_prefix=\"public_listener\"}[10m]))"
    }
   ]
  },
  {
   "title": "Is this service being sent requests?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{consul_destination_datacenter=\"dc1\",\nconsul_destination_service=~\"$service\"}[10m])) by (cluster, local_cluster)\n"
    }
   ]
  }
 ]
}