{
 "title": "Consul Service_To_Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(envoy_server_live, app)"
    }
   },
   {
    "name": "destination_service",
    "query": {
     "query": "label_values(envoy_server_live, app)"
    }
   },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  { "title": "TCP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TCP Downstream Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(envoy_tcp_downstream_cx_total) by (service, destination_service)"
    }
   ]
  },
  {
   "title": "TCP Original Destination Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(envoy_tcp_original_destination_downstream_cx_total) by (service, destination_service)\n"
    }
   ]
  },
  {
   "title": "Outbound Traffic Scenarios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Upstream Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{local_cluster=~\"$service\",\nconsul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster, consul_destination_service)"
    }
   ]
  },
  {
   "title": "Upstream Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\",local_cluster=~\"$service\",\nconsul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster, consul_destination_service) / sum(irate(envoy_cluster_upstream_rq_xx{local_cluster=~\"$service\",consul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster,consul_destination_service)\n"
    }
   ]
  },
  {
   "title": "Are requests from this service to its upstreams handled in a timely manner?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{local_cluster=~\"$service\",consul_destination_target!=\"\"}[10m])) by (le, consul_destination_target))",
     "legendFormat": "{{consul_destination_target}}"
    }
   ]
  },
  {
   "title": "Is Envoy's configuration growing stale?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "group(last_over_time(envoy_control_plane_connected_state{app=~\"$service\"}[10m] ) == 0) "
    }
   ]
  },
  { "title": "Inbound Traffic Scenarios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Response Success By Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{local_cluster=~\"$service\",envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (envoy_response_code_class)"
    }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\", consul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster) / sum(irate(envoy_cluster_upstream_rq_xx{consul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster)"
    }
   ]
  },
  {
   "title": "Requests Sent Per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{consul_destination_datacenter=\"dc1\",\nconsul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster)\n"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_destination_datacenter=\"dc1\",consul_destination_service=~\"$destination_service\",local_cluster!=\"\"}[10m])) by (le, cluster, local_cluster))"
    }
   ]
  },
  {
   "title": "Response Success Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_total{local_cluster=~\"$service\",envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (local_cluster)"
    }
   ]
  },
  {
   "title": "Request Response Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{local_cluster=~\"$service\",envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (local_cluster)"
    }
   ]
  }
 ]
}