env:
  GF_EXPLORE_ENABLED: true
  GF_PANELS_DISABLE_SANITIZE_HTML: true
  GF_LOG_FILTERS: rendering:debug
  GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
  GF_DATE_FORMATS_FULL_DATE: "MMM Do, YYYY hh:mm:ss a"
  GF_DATE_FORMATS_INTERVAL_SECOND: "hh:mm:ss a"
  GF_DATE_FORMATS_INTERVAL_MINUTE: "hh:mm a"
  GF_DATE_FORMATS_INTERVAL_HOUR: "DD/MM hh:mm a"
  GF_DATE_FORMATS_INTERVAL_DAY: "DD/MM"
  GF_DATE_FORMATS_INTERVAL_MONTH: "MM-YYYY"
  GF_DATE_FORMATS_INTERVAL_YEAR: "YYYY"
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  GF_AUTH_DISABLE_LOGIN_FORM: true

#adminPassword: admin

rbac:
  create: false
  pspEnabled: false

# Disable test pods
testFramework:
  enabled: false

podLabels:
  app: grafana

podAnnotations:
  "consul.hashicorp.com/connect-inject": "false"

service:
  port: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        orgId: 1
        url: http://prometheus-server.default.svc.cluster.local:80
        access: proxy
        isDefault: false
        jsonData:
          timeInterval: 5s
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.default.svc.cluster.local:3100/
        editable: true
        isDefault: true

persistence:
   type: pvc
   enabled: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'consuldataplanedashboard'
      orgId: 1
      allowUiUpdates: true
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/consuldataplanedashboard
    - name: 'consulservicedashboard'
      orgId: 1
      allowUiUpdates: true
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/consulservicedashboard
    - name: 'consulservicetoservicedashboard'
      orgId: 1
      allowUiUpdates: true
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/consulservicetoservicedashboard
    - name: 'grafanafinalaccesslogsanderrors'
      orgId: 1
      allowUiUpdates: true
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/grafanafinalaccesslogsanderrors

dashboardsConfigMaps:
  consuldataplanedashboard: consuldataplanedashboard
  consulservicedashboard: consulservicedashboard
  consulservicetoservicedashboard: consulservicetoservicedashboard
  grafanafinalaccesslogsanderrors: grafanafinalaccesslogsanderrors