global:
  name: consul
  datacenter: dc1

  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "2m"

ui:
  enabled: true
  service:
    type: NodePort
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server.default.svc.cluster.local

connectInject:
  enabled: true
  metrics:
    defaultEnabled: true
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer