global:
  name: consul
  datacenter: dc1

  metrics:
    enabled: true

ui:
  enabled: true
  service:
    type: NodePort
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server.default.svc.cluster.local

connectInject:
  enabled: true
  metrics:
    defaultEnabled: true
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer